[runtime] Stop using K&R function declarations
Legacy Classic Flang code uses K&R C function declarations, which differ
from ANSI C function declarations in that the parameters are not part of
the function prototype, which means that the functions can have unknown
numbers of parameters, of unknown types. With Clang 15, they will now
cause an warning message:

error: passing arguments to '__fort_gettb' without a prototype is deprecated in all versions of C and is not supported in C2x [-Werror,-Wdeprecated-non-prototype]

This commit rewrites all function declarations in modern C.